Repository man-group/PyBloqs, pull requests merged in 2025-04, with the labels that each got.

#164 Add CollapsibleBlock to pybloqs, add corresponding regression test
  pybloqs/__init__.py
  pybloqs/block/collapsible.py
  tests/regression/html_output/collapsible.html
  tests/regression/pybloqs_input/collapsible.py
Labels: enhancement

#166 Replace inner html
  pybloqs/server/provider.py
Labels: bug, server

#167 Use old compression library
  pybloqs/static/__init__.py
  pybloqs/static/jsinflate.js
  pybloqs/static/uncompressed/jsinflate.js
  pybloqs/util.py
  tests/regression/html_output/code.html
  tests/regression/html_output/collapsible.html
  tests/regression/html_output/empty.html
  tests/regression/html_output/flow.html
  tests/regression/html_output/grid.html
  tests/regression/html_output/hrule.html
  tests/regression/html_output/hstack.html
  tests/regression/html_output/markdown.html
  tests/regression/html_output/nested.html
  tests/regression/html_output/pre.html
  tests/regression/html_output/raw.html
  tests/regression/html_output/span.html
  tests/regression/html_output/title.html
  tests/regression/html_output/title_levels.html
  tests/regression/html_output/vstack.html
Labels: bug
