Repository man-group/PyBloqs, pull requests merged in 2025-01, with the labels that each got.

#142 Use browsers' DecompressionStream to do zlib decompression instead of rolling our own
  pybloqs/static/__init__.py
  pybloqs/static/jsinflate.js
  pybloqs/static/uncompressed/jsinflate.js
  pybloqs/util.py
  tests/regression/html_output/empty.html
  tests/regression/html_output/flow.html
  tests/regression/html_output/grid.html
  tests/regression/html_output/hrule.html
  tests/regression/html_output/hstack.html
  tests/regression/html_output/markdown.html
  tests/regression/html_output/nested.html
  tests/regression/html_output/pre.html
  tests/regression/html_output/raw.html
  tests/regression/html_output/span.html
  tests/regression/html_output/title.html
  tests/regression/html_output/title_levels.html
  tests/regression/html_output/vstack.html
  tests/unit/static/test_static.py
Labels: enhancement

#145 [bugfix] Make ids globally unique and HTML-valid for the session
  pybloqs/html.py
  tests/unit/test_html.py
Labels: bug

#140 Python 3.12 compatibility
  .circleci/config.yml
  pybloqs/__init__.py
  pybloqs/htmlconv/chrome_headless.py
  pybloqs/static/__init__.py
  pybloqs/util.py
  pyproject.toml
  setup.py
  tests/integration/generate/generation_framework.py
Labels: compatibility

#146 [bugfix] Render resources in iPython cells
  pybloqs/block/base.py
  tests/unit/block/test_base_unit.py
Labels: bug

#144 Pybloqs server
  .circleci/config.yml
  SECURITY.md
  docs/source/conf.py
  docs/source/getting_started/installation.md
  docs/source/index.md
  docs/source/server/demo.py
  docs/source/server/index.md
  pybloqs/server/__init__.py
  pybloqs/server/block/__init__.py
  pybloqs/server/block/life_loading.py
  pybloqs/server/block/poll.py
  pybloqs/server/block/refresh.py
  pybloqs/server/block/select.py
  pybloqs/server/block/tabs.py
  pybloqs/server/provider.py
  pybloqs/server/static/__init__.py
  pybloqs/server/static/htmx.min.js
  pyproject.toml
  tests/integration/test_server.py
  tests/unit/server/__init__.py
  tests/unit/server/test_provider.py
  tests/unit/server/test_server.py
Labels: enhancement
